// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tyuiu.teacher221.SidorovAY.Recipies.Data;

#nullable disable

namespace tyuiu.teacher221.SidorovAY.Recipies.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.Ingridient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MesureTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MesureTypeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingridients");
                });

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.MesureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MesureTypes");
                });

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.Ingridient", b =>
                {
                    b.HasOne("tyuiu.teacher221.SidorovAY.Recipies.Data.MesureType", "MesureType")
                        .WithMany("Ingridients")
                        .HasForeignKey("MesureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tyuiu.teacher221.SidorovAY.Recipies.Data.Recipe", "Recipe")
                        .WithMany("Ingridients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MesureType");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.Recipe", b =>
                {
                    b.HasOne("tyuiu.teacher221.SidorovAY.Recipies.Data.Category", "Category")
                        .WithMany("Recipies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.Category", b =>
                {
                    b.Navigation("Recipies");
                });

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.MesureType", b =>
                {
                    b.Navigation("Ingridients");
                });

            modelBuilder.Entity("tyuiu.teacher221.SidorovAY.Recipies.Data.Recipe", b =>
                {
                    b.Navigation("Ingridients");
                });
#pragma warning restore 612, 618
        }
    }
}
